# Build and test swift packages with GitVersion

trigger:
  batch: true
  branches:
    include:
      - master

pool:
  vmImage: 'macos-latest'

steps:

- script: swift package resolve
  failOnStderr: true
  displayName: 'swift package resolve'

- script: swift build --build-tests
  failOnStderr: true
  displayName: 'swift build -v -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios13.0-simulator"'
